import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider } from "@chakra-ui/react"
import { ReduxProvider } from '@/Lib/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Triviska Property',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
